<?php
/*
 *
 * Admin Menu
 * generated on 16 June 2017 05:35:02
 *
 *
 * This file is auto generated by Akane Console Tools
 * you can customize it to your need
 * for more information
 * type command "php console" from Akane directory on Terminal console
 * 
 */

if (!defined('_INC')) { die('404 Not Found'); }

$web->admin();

?>
			
	<li class="treeview">
        <a href="#">
            <i class="fa fa-newspaper-o"></i>
            <span>Article</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?php echo SITEURL; ?>?content=article&action=add"><i class="fa fa-plus"></i> Add</a></li>
            <li><a href="<?php echo SITEURL; ?>?content=article"><i class="fa fa-bars"></i> List</a></li>
        </ul>
    </li>
			
	<li class="treeview">
        <a href="#">
            <i class="fa fa-briefcase"></i>
            <span>Kategori</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?php echo SITEURL; ?>?content=kategori&action=add"><i class="fa fa-plus"></i> Add</a></li>
            <li><a href="<?php echo SITEURL; ?>?content=kategori"><i class="fa fa-bars"></i> List</a></li>
        </ul>
    </li>
			
	<li class="treeview">
        <a href="#">
            <i class="fa fa-shopping-bag"></i>
            <span>Sub Kategori</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?php echo SITEURL; ?>?content=sub_kategori&action=add"><i class="fa fa-plus"></i> Add</a></li>
            <li><a href="<?php echo SITEURL; ?>?content=sub_kategori"><i class="fa fa-bars"></i> List</a></li>
        </ul>
    </li>
