#!/usr/bin/env php
<?php

ini_set('display_errors', 1);

define('_INC' ,1);

/*
 * Database Config
 */

include "system/dbconfig.php";
echo $dbname;
$database_config = array
(
	'dbHost' => $dbHost,
	'dbUser' => $dbUser,
	'dbPass' => $dbPass,
	'dbname' => $dbname
);

include "system/cli/gen.php";
include "system/cli/cli.php";

$cli->set_db_config($database_config);

if ( isset($_SERVER['argv'][1]) ) {
	if ( !empty($_SERVER['argv'][1]) ){
		
		$param = $_SERVER['argv'][1];

		switch ($param) {
			case 'generate:all':
			case 'gen:all':
				echo $cli->generate_admin();
				break;
			case 'generate:single':
			case 'gen:sin':
				if ( isset($_SERVER['argv'][2]) ) {
					$tablename = $_SERVER['argv'][2];
				} else {
					$tablename = '';
				}
				echo $cli->generate_single_admin($tablename);
				break;
			case '--version':
			case '-v':
				echo $cli->version;
				break;
			case '--help':
			case '-h':
			default:
				echo $cli->show_help();
				break;
		}
	} else {
		echo $cli->show_help();
	}
} else {
	echo $cli->show_help();
}