<?php
/*
 *
 * Admin Menu
 * generated on 24 August 2014 04:46:01
 *
 *
 * This file is auto generated by Akane Console Tools
 * you can customize it to your need
 * for more information
 * type command "php console" from Akane directory on Terminal console
 * 
 */

if (!defined('_INC')) { die('404 Not Found'); }

$web->admin();

?>
	<li class="menu"><a href="javascript:void(0);">Master</a>
		<ul>
		</ul>
	</li>
