<?php
/*
 *
 * Admin Controller for table admin
 * generated on 24 August 2014 05:52:41
 *
 *
 * This file is auto generated by Akane Console Tools
 * you can customize it to your need
 * for more information
 * type command "php console" from Akane directory on Terminal console
 * 
 */

$web->admin();

load_model('admin');

if ( (isset($_GET['action'])) && (!empty($_GET['action'])) )
{
	$action = $_GET['action'];
} else {
	$action = '';
}
	switch($action)
	{
		case 'add':
			echo BACKLINK;
			if ( (isset($_POST['ppost'])) && ($_POST['ppost']==MENU_ADD) )
			{
				if (!empty($_POST['username']) && !empty($_POST['password']) && !empty($_POST['nama']) && !empty($_POST['level']) && !empty($_POST['status'])) {
					unset($_POST['ppost']);
					$_POST['action'] = 'insert';
					$_POST['table'] = 'admin';

					$web->db->auto_save();
					$web->gotopage(THISFILE);
				} else { echo ERROR_NULL; }
			}

			$this->forms
				->add('username', 'text', array('required' => true))
				->add('password', 'text', array('required' => true))
				->add('nama', 'text', array('required' => true))
				->add('level', 'text', array('required' => true))
				->add('status', 'text', array('required' => true))

			->renderForm(MENU_ADD);

		break;
		case 'edit':
			echo BACKLINK;
			if ( (isset($_GET['idb'])) && (!empty($_GET['idb'])) )
			{
				$idb = $_GET['idb'];
				$data = $web->admin->single($idb);
				$cb = count($data);
				if ($cb!=0)
				{
					$rb = $data[0];

					if ( (isset($_POST['ppost'])) && ($_POST['ppost']==MENU_EDIT) )
					{
						if (!empty($_POST['username']) && !empty($_POST['password']) && !empty($_POST['nama']) && !empty($_POST['level']) && !empty($_POST['status'])) {
							unset($_POST['ppost']);
							$_POST['action'] = 'update';
							$_POST['table'] = 'admin';
							$_POST['where'] = 'id='.$rb['id'];
							$web->db->auto_save();
							$web->gotopage(THISFILE);
						} else { echo ERROR_NULL; }
					}

					$this->forms
				->add('username', 'text', array('required' => true, 'value' => $rb['username']))
				->add('password', 'text', array('required' => true, 'value' => $rb['password']))
				->add('nama', 'text', array('required' => true, 'value' => $rb['nama']))
				->add('level', 'text', array('required' => true, 'value' => $rb['level']))
				->add('status', 'text', array('required' => true, 'value' => $rb['status']))

					->renderForm(MENU_EDIT);

				} else {
					echo ERROR_IDB_NULL;
				}
			} else {
				echo ERROR_IDB_NULL;
			}
		break;
		case 'delete':
			if ( (isset($_GET['idb'])) && (!empty($_GET['idb'])) )
			{
				$idb = $_GET['idb'];
				$data = $web->admin->single($idb);
				$cb = count($data);
				if ($cb!=0)
				{
					$rb = $data[0];
					$delete = $web->db->query_delete('admin',array('id' => $rb['id']));
					if ($delete){
						$web->gotopage(THISFILE);
					}
				} else {
					echo ERROR_IDB_NULL;
				}
			} else {
				echo ERROR_IDB_NULL;
			}
		break;
		default:
			$web->add_button();
			
			$data = $web->admin->all();
			$jmlrec = count($data);
			
			if ($jmlrec>0)
			{
				$x = 0;
				echo '<table width="100%" cellpadding="3" cellspacing="0" border="0">
				<tr>
					<td class="tabel-head2">Username</td>
					<td class="tabel-head2">Password</td>
					<td class="tabel-head2">Nama</td>
					<td class="tabel-head2">Level</td>
					<td class="tabel-head2">Status</td>
					<td width="50" class="tabel-head2-end" align="center">Action</td>
				</tr>';
				foreach($data as $data)
				{
					$color = ($x% 2  ? '' : ' class="diffcolor"');
					?>
					<tr<?php echo $color; ?>>
						<td class="tabel-content"><?php echo $data['username']; ?></td>
						<td class="tabel-content"><?php echo $data['password']; ?></td>
						<td class="tabel-content"><?php echo $data['nama']; ?></td>
						<td class="tabel-content"><?php echo $data['level']; ?></td>
						<td class="tabel-content"><?php echo $data['status']; ?></td>
						<td class="tabel-content-end" align="center">
							<?php echo $web->action_button('edit',THISFILE,$data['id']); ?>
							<?php echo $web->action_button('delete',THISFILE,$data['id'],'this data'); ?>
						</td>
					</tr>
					<?php
					$x++;
				}
				echo '</table>';
			} else {
				echo ERROR_EMPTY;
				echo "<br /><br />";
			}
		break;
	}
?>
