<?php
/*
 *
 * Admin Controller for table admin
 * generated on 16 June 2017 05:35:01
 *
 *
 * This file is auto generated by Akane Console Tools
 * you can customize it to your need
 * for more information
 * type command "php console" from Akane directory on Terminal console
 * 
 */

$web->admin();
$web->set_heading('Admin');

load_model('admin');

if ( (isset($_GET['action'])) && (!empty($_GET['action'])) )
{
	$action = $_GET['action'];
} else {
	$action = '';
}
	switch($action)
	{
		case 'add':
			$web->breadcumbs->add('?content=admin','Admin');
			$web->breadcumbs->add('current','Add');

			echo BACKLINK;

			if ( (isset($_POST['ppost'])) && ($_POST['ppost']==MENU_ADD) )
			{
				if (!empty($_POST['username']) && !empty($_POST['password']) && !empty($_POST['nama']) && !empty($_POST['level']) && !empty($_POST['status'])) {
					unset($_POST['ppost']);
					$_POST['action'] = 'insert';
					$_POST['table'] = 'admin';


					$web->db->auto_save();
					$web->gotopage(THISFILE);

				} else { echo ERROR_NULL; }
			}


			$this->forms
			->form_header('Add Admin')
				->add('username', 'text', array('required' => true))
				->add('password', 'text', array('required' => true))
				->add('nama', 'text', array('required' => true))
				->add('level', 'text', array('required' => true))
				->add('status', 'text', array('required' => true))

			->renderForm(MENU_ADD);

		break;
		case 'edit':
			$web->breadcumbs->add('?content=admin','Admin');
			$web->breadcumbs->add('current','Change');

			echo BACKLINK;

			if ( (isset($_GET['idb'])) && (!empty($_GET['idb'])) )
			{
				$idb = $_GET['idb'];
				$data = $web->admin->single($idb);
				$cb = count($data);
				if ($cb!=0)
				{
					$rb = $data[0];

					if ( (isset($_POST['ppost'])) && ($_POST['ppost']==MENU_EDIT) )
					{
						if (!empty($_POST['username']) && !empty($_POST['password']) && !empty($_POST['nama']) && !empty($_POST['level']) && !empty($_POST['status'])) {
							unset($_POST['ppost']);
							$_POST['action'] = 'update';
							$_POST['table'] = 'admin';
							$_POST['where'] = 'id='.$rb['id'];

							$web->db->auto_save();
							$web->gotopage(THISFILE);

						} else { echo ERROR_NULL; }
					}


					$this->forms
					->form_header('Change Admin')
				->add('username', 'text', array('required' => true, 'value' => $rb['username']))
				->add('password', 'text', array('required' => true, 'value' => $rb['password']))
				->add('nama', 'text', array('required' => true, 'value' => $rb['nama']))
				->add('level', 'text', array('required' => true, 'value' => $rb['level']))
				->add('status', 'text', array('required' => true, 'value' => $rb['status']))

					->renderForm(MENU_EDIT);

				} else {
					echo ERROR_IDB_NULL;
				}
			} else {
				echo ERROR_IDB_NULL;
			}
		break;
		case 'delete':
			if ( (isset($_GET['idb'])) && (!empty($_GET['idb'])) )
			{
				$idb = $_GET['idb'];
				$data = $web->admin->single($idb);
				$cb = count($data);
				if ($cb!=0)
				{
					$rb = $data[0];

					$delete = $web->db->query_delete('admin',array('id' => $rb['id']));
					if ($delete){
						$web->gotopage(THISFILE);
					}
				} else {
					echo ERROR_IDB_NULL;
				}
			} else {
				echo ERROR_IDB_NULL;
			}
		break;
		case 'view':
			$web->breadcumbs->add('?content=admin','Admin');
			$web->breadcumbs->add('current','View');
			
			echo BACKLINK;

			if ( (isset($_GET['idb'])) && (!empty($_GET['idb'])) )
			{
				$idb = $_GET['idb'];
				$data = $web->admin->single($idb);
				$cb = count($data);
				if ($cb!=0)
				{
					$rb = $data[0];
					$thead = array('id','username','password','nama','level','status');
					$web->forms->renderView($thead, $rb);
				} else {
					echo ERROR_IDB_NULL;
				}
			} else {
				echo ERROR_IDB_NULL;
			}			
		break;
		default:
			$web->breadcumbs->add('current','Admin');
			$web->forms->topbar();

			$keyword = '';
			$searchlink = '';
			if (isset($_GET['keyword'])){
				$keyword = $_GET['keyword'];
				$searchlink = '&keyword='.$_GET['keyword'];
			}
			
			$data = $web->admin->all('',$keyword);
			$jmlrec = count($data);
			
			$url = SITEURL.'?content='.THISFILE.$searchlink.'&paged=[[paged]]';
            $paging = $web->pagination_seo($jmlrec, $url);
            
            $data = $web->admin->all($paging['limit'],$keyword);
            $jmlr = count($data);
            
			if ($jmlrec>0)
			{
				$thead = array('id','username','password','nama','level','status','action' => array('view','edit','delete'));
				$web->forms->renderTable($thead, $data);
				echo $paging['output'];
			} else {
				echo ERROR_EMPTY;
				echo "<br /><br />";
			}
		break;
	}

