<?php
/*
 *
 * Admin Menu
 * generated on 25 August 2014 13:32:05
 *
 *
 * This file is auto generated by Akane Console Tools
 * you can customize it to your need
 * for more information
 * type command "php console" from Akane directory on Terminal console
 * 
 */

if (!defined('_INC')) { die('404 Not Found'); }

$web->admin();

?>
<li class="menu"><a href="<?php echo SITEURL; ?>?content=admin">Admin</a></li>
