<?php
/*
 *
 * Admin Controller for table config
 * generated on 16 June 2017 05:35:02
 *
 *
 * This file is auto generated by Akane Console Tools
 * you can customize it to your need
 * for more information
 * type command "php console" from Akane directory on Terminal console
 * 
 */

$web->admin();
$web->set_heading('Config');

load_model('config');

if ( (isset($_GET['action'])) && (!empty($_GET['action'])) )
{
	$action = $_GET['action'];
} else {
	$action = '';
}
	switch($action)
	{
		case 'add':
			$web->breadcumbs->add('?content=config','Config');
			$web->breadcumbs->add('current','Add');

			echo BACKLINK;

			if ( (isset($_POST['ppost'])) && ($_POST['ppost']==MENU_ADD) )
			{
				if (!empty($_POST['config_edit']) && !empty($_POST['config_name']) && !empty($_POST['config_value']) && !empty($_POST['config_desc'])) {
					unset($_POST['ppost']);
					$_POST['action'] = 'insert';
					$_POST['table'] = 'config';


					$web->db->auto_save();
					$web->gotopage(THISFILE);

				} else { echo ERROR_NULL; }
			}


			$this->forms
			->form_header('Add Config')
				->add('config_edit', 'text', array('required' => true))
				->add('config_name', 'text', array('required' => true))
				->add('config_value', 'textarea', array('required' => true))
				->add('config_desc', 'textarea', array('required' => true))

			->renderForm(MENU_ADD);

		break;
		case 'edit':
			$web->breadcumbs->add('?content=config','Config');
			$web->breadcumbs->add('current','Change');

			echo BACKLINK;

			if ( (isset($_GET['idb'])) && (!empty($_GET['idb'])) )
			{
				$idb = $_GET['idb'];
				$data = $web->config->single($idb);
				$cb = count($data);
				if ($cb!=0)
				{
					$rb = $data[0];

					if ( (isset($_POST['ppost'])) && ($_POST['ppost']==MENU_EDIT) )
					{
						if (!empty($_POST['config_edit']) && !empty($_POST['config_name']) && !empty($_POST['config_value']) && !empty($_POST['config_desc'])) {
							unset($_POST['ppost']);
							$_POST['action'] = 'update';
							$_POST['table'] = 'config';
							$_POST['where'] = 'config_id='.$rb['config_id'];

							$web->db->auto_save();
							$web->gotopage(THISFILE);

						} else { echo ERROR_NULL; }
					}


					$this->forms
					->form_header('Change Config')
				->add('config_edit', 'text', array('required' => true, 'value' => $rb['config_edit']))
				->add('config_name', 'text', array('required' => true, 'value' => $rb['config_name']))
				->add('config_value', 'textarea', array('required' => true, 'value' => $rb['config_value']))
				->add('config_desc', 'textarea', array('required' => true, 'value' => $rb['config_desc']))

					->renderForm(MENU_EDIT);

				} else {
					echo ERROR_IDB_NULL;
				}
			} else {
				echo ERROR_IDB_NULL;
			}
		break;
		case 'delete':
			if ( (isset($_GET['idb'])) && (!empty($_GET['idb'])) )
			{
				$idb = $_GET['idb'];
				$data = $web->config->single($idb);
				$cb = count($data);
				if ($cb!=0)
				{
					$rb = $data[0];

					$delete = $web->db->query_delete('config',array('config_id' => $rb['config_id']));
					if ($delete){
						$web->gotopage(THISFILE);
					}
				} else {
					echo ERROR_IDB_NULL;
				}
			} else {
				echo ERROR_IDB_NULL;
			}
		break;
		case 'view':
			$web->breadcumbs->add('?content=config','Config');
			$web->breadcumbs->add('current','View');
			
			echo BACKLINK;

			if ( (isset($_GET['idb'])) && (!empty($_GET['idb'])) )
			{
				$idb = $_GET['idb'];
				$data = $web->config->single($idb);
				$cb = count($data);
				if ($cb!=0)
				{
					$rb = $data[0];
					$thead = array('config_id','config_edit','config_name','config_value','config_desc');
					$web->forms->renderView($thead, $rb);
				} else {
					echo ERROR_IDB_NULL;
				}
			} else {
				echo ERROR_IDB_NULL;
			}			
		break;
		default:
			$web->breadcumbs->add('current','Config');
			$web->forms->topbar();

			$keyword = '';
			$searchlink = '';
			if (isset($_GET['keyword'])){
				$keyword = $_GET['keyword'];
				$searchlink = '&keyword='.$_GET['keyword'];
			}
			
			$data = $web->config->all('',$keyword);
			$jmlrec = count($data);
			
			$url = SITEURL.'?content='.THISFILE.$searchlink.'&paged=[[paged]]';
            $paging = $web->pagination_seo($jmlrec, $url);
            
            $data = $web->config->all($paging['limit'],$keyword);
            $jmlr = count($data);
            
			if ($jmlrec>0)
			{
				$thead = array('config_id','config_edit','config_name','config_value','config_desc','action' => array('view','edit','delete'));
				$web->forms->renderTable($thead, $data);
				echo $paging['output'];
			} else {
				echo ERROR_EMPTY;
				echo "<br /><br />";
			}
		break;
	}

