<?php
/*
 *
 * Admin Controller for table config
 * generated on 24 August 2014 04:46:01
 *
 *
 * This file is auto generated by Akane Console Tools
 * you can customize it to your need
 * for more information
 * type command "php console" from Akane directory on Terminal console
 * 
 */

$web->admin();

load_model('config');

if ( (isset($_GET['action'])) && (!empty($_GET['action'])) )
{
	$action = $_GET['action'];
} else {
	$action = '';
}
	switch($action)
	{
		case 'add':
			echo BACKLINK;
			if ( (isset($_POST['ppost'])) && ($_POST['ppost']==MENU_ADD) )
			{
				if (!empty($_POST['config_edit']) && !empty($_POST['config_name']) && !empty($_POST['config_value']) && !empty($_POST['config_desc'])) {
					unset($_POST['ppost']);
					$_POST['action'] = 'insert';
					$_POST['table'] = 'config';
					$_POST['create_date'] = 'NOW()';
					$web->db->auto_save();
					$web->gotopage(THISFILE);
				} else { echo ERROR_NULL; }
			}

			$this->forms
				->add('config_edit', 'text', array('required' => true))
				->add('config_name', 'text', array('required' => true))
				->add('config_value', 'textarea', array('required' => true))
				->add('config_desc', 'textarea', array('required' => true))

			->renderForm(MENU_ADD);

		break;
		case 'edit':
			echo BACKLINK;
			if ( (isset($_GET['idb'])) && (!empty($_GET['idb'])) )
			{
				$idb = $_GET['idb'];
				$data = $web->config->single($idb);
				$cb = count($data);
				if ($cb!=0)
				{
					$rb = $data[0];

					if ( (isset($_POST['ppost'])) && ($_POST['ppost']==MENU_EDIT) )
					{
						if (!empty($_POST['config_edit']) && !empty($_POST['config_name']) && !empty($_POST['config_value']) && !empty($_POST['config_desc'])) {
							unset($_POST['ppost']);
							$_POST['action'] = 'update';
							$_POST['table'] = 'config';
							$_POST['where'] = 'config_id='.$rb['config_id'];
							$web->db->auto_save();
							$web->gotopage(THISFILE);
						} else { echo ERROR_NULL; }
					}

					$this->forms
				->add('config_edit', 'text', array('required' => true, 'value' => $rb['config_edit']))
				->add('config_name', 'text', array('required' => true, 'value' => $rb['config_name']))
				->add('config_value', 'textarea', array('required' => true, 'value' => $rb['config_value']))
				->add('config_desc', 'textarea', array('required' => true, 'value' => $rb['config_desc']))

					->renderForm(MENU_EDIT);

				} else {
					echo ERROR_IDB_NULL;
				}
			} else {
				echo ERROR_IDB_NULL;
			}
		break;
		case 'delete':
			if ( (isset($_GET['idb'])) && (!empty($_GET['idb'])) )
			{
				$idb = $_GET['idb'];
				$data = $web->config->single($idb);
				$cb = count($data);
				if ($cb!=0)
				{
					$rb = $data[0];
					$delete = $web->db->query_delete('config',array('config_id' => $rb['config_id']));
					if ($delete){
						$web->gotopage(THISFILE);
					}
				} else {
					echo ERROR_IDB_NULL;
				}
			} else {
				echo ERROR_IDB_NULL;
			}
		break;
		default:
			$web->add_button();
			
			$data = $web->config->all();
			$jmlrec = count($data);
			
			if ($jmlrec>0)
			{
				$x = 0;
				echo '<table width="100%" cellpadding="3" cellspacing="0" border="0">
				<tr>
					<td class="tabel-head2">Config Edit</td>
					<td class="tabel-head2">Config Name</td>
					<td class="tabel-head2">Config Value</td>
					<td class="tabel-head2">Config Desc</td>
					<td width="50" class="tabel-head2-end" align="center">Action</td>
				</tr>';
				foreach($data as $data)
				{
					$color = ($x% 2  ? '' : ' class="diffcolor"');
					?>
					<tr<?php echo $color; ?>>
						<td class="tabel-content"><?php echo $data['config_edit']; ?></td>
						<td class="tabel-content"><?php echo $data['config_name']; ?></td>
						<td class="tabel-content"><?php echo $data['config_value']; ?></td>
						<td class="tabel-content"><?php echo $data['config_desc']; ?></td>
						<td class="tabel-content-end" align="center">
							<?php echo $web->action_button('edit',THISFILE,$data['config_id']); ?>
							<?php echo $web->action_button('delete',THISFILE,$data['config_id'],'this data'); ?>
						</td>
					</tr>
					<?php
					$x++;
				}
				echo '</table>';
			} else {
				echo ERROR_EMPTY;
				echo "<br /><br />";
			}
		break;
	}
?>
