<?php
/*
 *
 * Admin Controller for table sub_kategori
 * generated on 28 October 2014 14:25:58
 *
 *
 * This file is auto generated by Akane Console Tools
 * you can customize it to your need
 * for more information
 * type command "php console" from Akane directory on Terminal console
 * 
 */

$web->admin();

load_model('kategori');
load_model('sub_kategori');

if ( (isset($_GET['action'])) && (!empty($_GET['action'])) )
{
	$action = $_GET['action'];
} else {
	$action = '';
}
	switch($action)
	{
		case 'add':
			echo BACKLINK;
			if ( (isset($_POST['ppost'])) && ($_POST['ppost']==MENU_ADD) )
			{
				if (!empty($_POST['id_kategori']) && !empty($_POST['name'])) {
					unset($_POST['ppost']);
					$_POST['action'] = 'insert';
					$_POST['table'] = 'sub_kategori';

					$web->db->auto_save();
					$web->gotopage(THISFILE);
				} else { echo ERROR_NULL; }
			}

			$this->forms
				# Change primary_column and display_column to your need
				->add('id_kategori', 'relation', array('required' => true, 'table' => 'kategori', 'primary_column' => 'id', 'display_column' => 'name'))
				->add('name', 'text', array('required' => true))

			->renderForm(MENU_ADD);

		break;
		case 'edit':
			echo BACKLINK;
			if ( (isset($_GET['idb'])) && (!empty($_GET['idb'])) )
			{
				$idb = $_GET['idb'];
				$data = $web->sub_kategori->single($idb);
				$cb = count($data);
				if ($cb!=0)
				{
					$rb = $data[0];

					if ( (isset($_POST['ppost'])) && ($_POST['ppost']==MENU_EDIT) )
					{
						if (!empty($_POST['id_kategori']) && !empty($_POST['name'])) {
							unset($_POST['ppost']);
							$_POST['action'] = 'update';
							$_POST['table'] = 'sub_kategori';
							$_POST['where'] = 'id='.$rb['id'];
							$web->db->auto_save();
							$web->gotopage(THISFILE);
						} else { echo ERROR_NULL; }
					}

					$this->forms
				# Change primary_column and display_column to your need
				->add('id_kategori', 'relation', array('required' => true, 'table' => 'kategori', 'primary_column' => 'id', 'display_column' => 'name', 'value' => $rb['id_kategori']))
				->add('name', 'text', array('required' => true, 'value' => $rb['name']))

					->renderForm(MENU_EDIT);

				} else {
					echo ERROR_IDB_NULL;
				}
			} else {
				echo ERROR_IDB_NULL;
			}
		break;
		case 'delete':
			if ( (isset($_GET['idb'])) && (!empty($_GET['idb'])) )
			{
				$idb = $_GET['idb'];
				$data = $web->sub_kategori->single($idb);
				$cb = count($data);
				if ($cb!=0)
				{
					$rb = $data[0];
					$delete = $web->db->query_delete('sub_kategori',array('id' => $rb['id']));
					if ($delete){
						$web->gotopage(THISFILE);
					}
				} else {
					echo ERROR_IDB_NULL;
				}
			} else {
				echo ERROR_IDB_NULL;
			}
		break;
		default:
			$web->add_button();
			$web->search_form();
			
			$keyword = '';
			$searchlink = '';
			if (isset($_GET['keyword'])){
				$keyword = $_GET['keyword'];
				$searchlink = '&keyword='.$_GET['keyword'];
			}
			
			$data = $web->sub_kategori->all('',$keyword);
			$jmlrec = count($data);
			
			$url = SITEURL.'?content='.THISFILE.$searchlink.'&paged=[[paged]]';
            $paging = $web->pagination_seo($jmlrec, $url);
            
            $data = $web->sub_kategori->all($paging['limit'],$keyword);
            $jmlr = count($data);
            
			if ($jmlrec>0)
			{
				$x = 0;
				echo '<table width="100%" cellpadding="3" cellspacing="0" border="0">
				<tr>
					<td class="tabel-head2">Kategori</td>
					<td class="tabel-head2">Name</td>
					<td width="50" class="tabel-head2-end" align="center">Action</td>
				</tr>';
				foreach($data as $data)
				{
					$color = ($x% 2  ? '' : ' class="diffcolor"');
					$kategori = $web->kategori->name($data['id_kategori']);
					?>
					<tr<?php echo $color; ?>>
						<td class="tabel-content"><?php echo $kategori; ?></td>
						<td class="tabel-content"><?php echo $data['name']; ?></td>
						<td class="tabel-content-end" align="center">
							<?php echo $web->action_button('edit',THISFILE,$data['id']); ?>
							<?php echo $web->action_button('delete',THISFILE,$data['id'],'this data'); ?>
						</td>
					</tr>
					<?php
					$x++;
				}
				echo '</table>';
				echo $paging['output'];
			} else {
				echo ERROR_EMPTY;
				echo "<br /><br />";
			}
		break;
	}
?>
