<?php
/*
 *
 * Model Class for table admin
 * generated on 24 August 2014 05:52:41
 *
 *
 * This file is auto generated by Akane Console Tools
 * you can customize it to your need
 * for more information
 * type command "php console" from Akane directory on Terminal console
 * 
 */
class admin
{
	var $main;
	
	function __construct() {
		$this->main = get_instance();
	}
	
	function single($id){
		return $this->main->db->get_data('admin', '', "id='$id'");
	}
	
	function all(){
		$data = $this->main->db->get_data('admin');
		return $data;
	}
	
}
