<?php
/*
 *
 * Model Class for table admin
 * generated on 25 August 2014 13:32:05
 *
 *
 * This file is auto generated by Akane Console Tools
 * you can customize it to your need
 * for more information
 * type command "php console" from Akane directory on Terminal console
 * 
 */
class admin
{
	var $main;
	
	function __construct() {
		$this->main = get_instance();
	}
	
	function single($id){
		return $this->main->db->get_data('admin', '', "id='$id'");
	}
	
	function all($limit='',$keyword=''){
		$where = '';
		if ($keyword!=''){
			# please change this searchable column name to your need
			$where = "id LIKE '%$keyword%'";
		}
		$data = $this->main->db->get_data('admin', '', $where, '', $limit);
		return $data;
	}	
}
