<?php
/*
 *
 * Model Class for table config
 * generated on 16 June 2017 05:35:02
 *
 *
 * This file is auto generated by Akane Console Tools
 * you can customize it to your need
 * for more information
 * type command "php console" from Akane directory on Terminal console
 * 
 */
class config
{
	var $main;
	
	function __construct() {
		$this->main = get_instance();
	}
	
	function single($id){
		return $this->main->db->get_data('config', '', "id='$id'");
	}
	
	function name($id){
		$data = $this->main->db->get_data('config', '', "id='$id'");
		return $data[0]['name']; # change this to field that contain name
	}

	function all($section='', $limit='', $keyword='')
	{
		$where = '';
		if ($section!=''){
			$where = "config_category='".$section."'";
		}

		if ($keyword!=''){
			$searchable = array('config_name','config_value','config_desc');

			if (count($searchable) > 1){
				$wheres = array();
				foreach ($searchable as $field){
					$wheres[] = $field." LIKE '%".$keyword."%'";
				}
				$where = implode(' OR ',$wheres);
			} else {
				$where = $searchable[0]." LIKE '%".$keyword."%'";
			}
		}
		$data = $this->main->db->get_data('config', '', $where, 'config_desc ASC', $limit);
		return $data;
	}	
}
